version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.22.0
    restart: always
    ports:
      - "9090:9090"
    links:
      - blackbox_exporter
      - alertmanager
    volumes:
      - "./config:/config"
      - "prometheus-storage:/data"
    command:
      - '--config.file=/config/prometheus.yml'
      - '--storage.tsdb.retention.time=720h'
      - '--storage.tsdb.path=/data'
    user: root

  blackbox_exporter:
    image: prom/blackbox-exporter:v0.18.0
    restart: always
    ports:
      - "9115:9115"
    volumes:
      - "./config:/config"
    command: --config.file=/config/blackbox.yml

  node-exporter:
    image: prom/node-exporter:v1.0.1
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: always
    ports:
      - "9100:9100"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.38.6
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /cgroup:/cgroup:ro #doesn't work on MacOS only for Linux
    restart: always
    ports:
      - "8080:8080"

  alertmanager:
    image: prom/alertmanager:v0.21.0
    restart: always
    ports:
      - "9093:9093"
    volumes:
      - "./data/alertmanager:/data"
      - "./config:/config"
    command: --config.file=/config/alertmanager.yml --storage.path=/data
    user: "1000:1000"

  grafana:
    image: grafana/grafana:7.3.1
    ports:
      - '3000:3000'
    restart: always
    volumes:
      - "./data/grafana/provisioning/:/etc/grafana/provisioning/"
      - "grafana-storage:/var/lib/grafana"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_SERVER_ROOT_URL=${GRAFANA_ROOT_URL}

volumes:
  grafana-storage:
  prometheus-storage:
