global:
  slack_api_url: ''
  resolve_timeout: 1m

route:
  receiver: 'slack-notifications'
  group_by: [instance, severity, app]
  group_interval: 1m
  routes:
    - match:
        type: http
        severity: page
      receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
    - channel: '#monitoring-alert'
      text: "<!channel> \nSummary: {{ .CommonAnnotations.description }}. Please check {{ .GroupLabels.instance }}"
      send_resolved: true

