global:
    scrape_interval: 15s
    external_labels:
        monitor: 'prometheus-monitoring'
rule_files:
  - '/config/prometheus-rules.yml'
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
         - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    scrape_interval: 15s
    static_configs:
         - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    scrape_interval: 15s
    static_configs:
         - targets: ['cadvisor:8080']
  - job_name: 'blackbox_exporter'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - "example.com"  # Target to probe with https.
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115  # The blackbox exporter's real hostname:port.

  - job_name: 'blackbox-https'
    metrics_path: /probe
    params:
      module: [http_2xx]
    file_sd_configs:
      - files: ['/config/blackbox_http_targets.yml']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 'alertmanager:9093'

